// web_modules/yyvip-vue/pageAlert.vue
<template lang="pug">
page-modal(:showPageModal="showPageModal", :onClickMask="onClickMask", :hideOnClickMask="hideOnClickMask", :hidePageModal="hidePageModal", :pageModalClass="pageModalClass", :showClose="showClose", :onClickClose="onClickClose", :hideOnClickClose="hideOnClickClose")
  .page-alert__body(slot="body")
    slot
  .page-alert__foot(slot="foot" @click.stop.prevent="bindConfirm($event)") {{ alertButtonText }}
</template>

<script>
import pageModal from 'yyvip-vue/pageModal'

export default {
  name: 'pageAlert',
  components: {
    pageModal
  },
  props: {
    showClose: {
      type: Boolean,
      required: false,
      default: false
    },
    onClickClose: {
      type: Function,
      required: false
    },
    hideOnClickClose: {
      type: Boolean,
      required: false,
      default: true
    },
    showPageModal: {
      type: Boolean,
      required: true
    },
    onClickMask: {
      type: Function,
      required: false
    },
    hideOnClickMask: {
      type: Boolean,
      required: false,
      default: true
    },
    hidePageModal: {
      type: Function,
      required: false
    },
    pageModalClass: {
      type: Object,
      required: false
    },
    alertButtonText: {
      type: String,
      required: false,
      default: '确定'
    },
    onConfirm: {
      type: Function,
      required: false
    },
    hideOnConfirm: {
      type: Boolean,
      required: false,
      default: true
    }
  },
  methods: {
    bindConfirm(e) {
      this.onConfirm && this.onConfirm(e)
      this.hideOnConfirm && this.hidePageModal && this.hidePageModal(e)
    }
  }
}
</script>

<style lang="stylus">
@import '../yyvip-stylus/base'

.page-alert__foot
  height 88spx
  color color-blue
  line-height 88spx
  border-top 1PX solid border-grey
</style>

// web_modules/yyvip-react/PageAlert/index.jsx
import React from 'react'
import PropTypes from 'prop-types'
import PageModal from '../PageModal'

import './pageAlert.styl'

const PageAlert = ({
  alertButtonText = '确定', children, onConfirm, hideOnConfirm = true, hidePageModal, ...props
}) => {
  const bindConfirm = (e) => {
    e.stopPropagation()
    onConfirm && onConfirm(e)
    hideOnConfirm && hidePageModal && hidePageModal(e)
  }
  return (
    <PageModal hidePageModal={hidePageModal} {...props}>
      <div className='page-modal__main__box__body'>
        <div className='page-alert__body'>{children}</div>
      </div>
      <div className='page-modal__main__box__foot'>
        <div className='page-alert__foot' onClick={bindConfirm}>{alertButtonText}</div>
      </div>
    </PageModal>
  )
}

PageAlert.propTypes = {
  children: PropTypes.node,
  showClose: PropTypes.bool,
  onConfirm: PropTypes.func,
  onClickMask: PropTypes.func,
  onClickClose: PropTypes.func,
  hideOnConfirm: PropTypes.bool,
  hidePageModal: PropTypes.func,
  hideOnClickMask: PropTypes.bool,
  hideOnClickClose: PropTypes.bool,
  alertButtonText: PropTypes.string,
  isShow: PropTypes.bool.isRequired,
  pageModalClass: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.object,
    PropTypes.string
  ])
}

export default PageAlert
