// web_modules/yyvip-react/BottomSelect/index.jsx
import React from 'react'
import PropTypes from 'prop-types'
import classnames from 'classnames'
import BottomLayer from '../BottomLayer'
import ReactIf from '../property/ReactIf'

import './bottomSelect.styl'

function getDisplayValue(input) {
  return typeof input !== 'object' ? input : (input.displayValue || input.text || input.value || input.val)
}

const BottomSelect = ({
  showCancle = true, cancelText = '取消', activeIndex, selectItems, onClickItem, onClickCancel, hideOnClickItem = true, hideOnClickCancel = true, hideBottomLayer, bottomSelectClass = 'bottom-select--default', children, ...props
}) => {
  const bindClickItem = (e, index) => {
    e.stopPropagation()
    onClickItem && onClickItem(e, index)
    hideOnClickItem && hideBottomLayer && hideBottomLayer(e)
  }
  const bindClickCancel = (e) => {
    e.stopPropagation()
    onClickCancel && onClickCancel(e)
    hideOnClickCancel && hideBottomLayer && hideBottomLayer(e)
  }
  return (
    <BottomLayer hideBottomLayer={hideBottomLayer} {...props}>
      <div className={classnames('bottom-select', bottomSelectClass)}>
        {children}
        <ul className='bottom-select__box'>
          {
            selectItems.map((item, index) => (
              <li key={getDisplayValue(item)} className={classnames('bottom-select__box__item', { active: index === activeIndex })} onClick={(e) => bindClickItem(e, index)}>{getDisplayValue(item)}</li>
            ))
          }
        </ul>
        <ReactIf show={showCancle}>
          <div className='bottom-select__cancel' onClick={bindClickCancel}>{cancelText}</div>
        </ReactIf>
      </div>
    </BottomLayer>
  )
}

BottomSelect.propTypes = {
  children: PropTypes.node,
  showCancle: PropTypes.bool,
  cancelText: PropTypes.string,
  activeIndex: PropTypes.number,
  onClickItem: PropTypes.func,
  onClickCancel: PropTypes.func,
  hideOnClickItem: PropTypes.bool,
  hideOnClickCancel: PropTypes.bool,
  onClickMask: PropTypes.func,
  hideBottomLayer: PropTypes.func,
  hideOnClickMask: PropTypes.bool,
  show: PropTypes.bool.isRequired,
  selectItems: PropTypes.array.isRequired,
  bottomLayerClass: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.object,
    PropTypes.string
  ]),
  bottomSelectClass: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.object,
    PropTypes.string
  ])
}

export default BottomSelect

// web_modules/yyvip-vue/bottomSelect.vue
<template lang="pug">
bottomLayer(:show="show", :hideBottomLayer="hideBottomLayer", :bottomLayerClass="bottomLayerClass", :onClickMask="onClickMask", :hideOnClickMask="hideOnClickMask")
  .b__bottom-select(v-bind:class="bottomSelectClass")
    slot
    ul.__box
      li.__item(v-for="(item, index) in selectItems", @click.stop.prevent="bindClickItem(index, $event)", :class="{active: index === activeIndex}") {{ item | getDisplayValue }}
    .__cancel(v-if="showCancle",  @click.stop.prevent="bindClickCancel($event)") {{ cancelText }}
</template>

<script>
import bottomLayer from 'yyvip-vue/bottomLayer'

export default {
  name: 'bottomSelect',
  components: {
    bottomLayer
  },
  props: {
    show: {
      type: Boolean,
      required: true
    },
    onClickMask: {
      type: Function,
      required: false
    },
    hideOnClickMask: {
      type: Boolean,
      required: false,
      default: true
    },
    hideBottomLayer: {
      type: Function,
      required: false
    },
    bottomLayerClass: {
      type: Object,
      required: false
    },
    showCancle: {
      type: Boolean,
      required: false,
      default: true
    },
    cancelText: {
      type: String,
      required: false,
      default: '取消'
    },
    activeIndex: {
      type: Number,
      required: false
    },
    selectItems: {
      type: Array,
      required: true
    },
    onClickItem: {
      type: Function,
      required: false
    },
    hideOnClickItem: {
      type: Boolean,
      required: false,
      default: true
    },
    onClickCancel: {
      type: Function,
      required: false
    },
    hideOnClickCancel: {
      type: Boolean,
      required: false,
      default: true
    },
    bottomSelectClass: {
      type: Object,
      required: false,
      default: () => ({ 'bottom-select--default': true })
    }
  },
  filters: {
    getDisplayValue(input) {
      return typeof input !== 'object' ? input : (input.displayValue || input.text || input.value || input.val)
    }
  },
  methods: {
    bindClickItem(index, e) {
      this.onClickItem && this.onClickItem(index, e)
      this.hideOnClickItem && this.hideBottomLayer && this.hideBottomLayer(e)
    },
    bindClickCancel(e) {
      this.onClickCancel && this.onClickCancel(e)
      this.hideOnClickCancel && this.hideBottomLayer && this.hideBottomLayer(e)
    }
  }
}
</script>

<style lang="stylus">
@import '../yyvip-stylus/base'
 
.bottom-select--default
  .bottom-select
    &__cancel
      preHeight(90spx)
      color color-grey
    &__box
      &__item
        preHeight(90spx)
        border-bottom 1PX solid border-grey
        &.active
          color color-blue
</style>
