// web_modules/yyvip-react/CountDown/index.jsx
import React, { PureComponent} from 'react'
import PropTypes from 'prop-types'
import classnames from 'classnames'

import './countDown.styl'

const noop = () => {}

export default class CountDown extends PureComponent {
  static defaultProps = {
    maxTime: 60,
    onStart: noop,
    onDisabled: noop,
    onNoneClickable: noop,
    activeText: '获取验证码',
    disabledText: '重新发送',
    styleClass: 'count-down--default'
  }

  constructor(...args) {
    super(...args)
    this.timer = null
    this.state = { time: 0, disabled: false }
    this.reset = this.reset.bind(this)
    this.bindClick = this.bindClick.bind(this)
  }

  bindClick(e) {
    e.stopPropagation()
    const { maxTime, onStart, clickable, onDisabled, onNoneClickable } = this.props
    if (!clickable) {
      onNoneClickable(e)
    } else if (this.state.disabled) {
      onDisabled(e)
    } else {
      onStart(e)
      this.setState({ disabled: true })
      this.timer = setInterval(() => {
        this.setState({ time: this.state.time + 1 }, () => this.state.time >= maxTime && this.reset())
      }, 1000)
    }
  }

  reset() {
    clearInterval(this.timer)
    this.setState({ time: 0, disabled: false })
  }

  render() {
    const {
      time,
      disabled
    } = this.state
    const {
      maxTime,
      styleClass,
      activeText,
      disabledText
    } = this.props
    return <div className={classnames('count-down', styleClass, { active: !disabled, disabled: disabled })} onClick={this.bindClick}>{disabled ? `${disabledText}(${maxTime - time}S)` : activeText}</div>
  }
}

CountDown.propTypes = {
  onStart: PropTypes.func,
  maxTime: PropTypes.number,
  activeText: PropTypes.string,
  onDisabled: PropTypes.func,
  disabledText: PropTypes.string,
  onNoneClickable: PropTypes.func,
  clickable: PropTypes.bool.isRequired,
  styleClass: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.object,
    PropTypes.string
  ])
}

// web_modules/yyvip-vue/countDown.vue
<template lang="pug">
.count-down(@click.stop.prevent="bindClick", :class="classObj") {{ showText }}
</template>

<script>
import assign from 'lodash/assign'

const noop = () => {}

export default {
  name: 'countDown',
  props: {
    clickable: {
      type: Boolean,
      required: true
    },
    onStart: {
      type: Function,
      required: false,
      default: noop
    },
    activeText: {
      type: String,
      required: false,
      default: '获取验证码'
    },
    disabledText: {
      type: String,
      required: false,
      default: '重新发送'
    },
    maxTime: {
      type: Number,
      required: false,
      default: 60
    },
    onNoneClickable: {
      type: Function,
      required: false,
      default: noop
    },
    onDisabled: {
      type: Function,
      required: false,
      default: noop
    },
    styleClass: {
      type: Object,
      required: false,
      default: () => ({ 'count-down--default': true })
    }
  },
  data() {
    return {
      time: 0,
      timer: null,
      disabled: false
    }
  },
  methods: {
    bindClick(e) {
      if (!this.clickable) {
        this.onNoneClickable(e)
      } else if (this.disabled) {
        this.onDisabled(e)
      } else {
        this.onStart(e)
        this.disabled = true
        this.timer = setInterval(() => {
          this.time++
          this.time >= this.maxTime && this.reset()
        }, 1000)
      }
    },
    reset() {
      this.time = 0
      this.disabled = false
      clearInterval(this.timer)
    }
  },
  computed: {
    showText() {
      return this.disabled ? `${this.disabledText}(${this.maxTime - this.time}S)` : this.activeText
    },
    classObj() {
      return assign({
        active: !this.disabled,
        disabled: this.disabled
      }, this.styleClass)
    }
  }
}
</script>

<style lang="stylus">
@import '../yyvip-stylus/base'

.count-down
  fontDpr(14)
  &--default
    color #fff
    width 240spx
    preHeight(80spx)
    text-align center
    &.active
      background color-blue
    &.disabled
      background color-grey
</style>
