// web_modules/yyvip-vue/scrollToTop.vue
<template lang="pug">
transition(name="scroll-to-top")
  p.b__scroll-to-top(v-if="showToTop" @click.stop.prevent="scrollToTop" v-bind:class="classObject")
</template>

<script>
import { getDpr } from '../yyvip-flexible/utils'
import { scrollTop } from '../yyvip-utils/checkBrowser'

const dpr = getDpr()

export default {
  name: 'scrollToTop',
  data() {
    return {
      showToTop: false
    }
  },
  props: {
    scrollToTopClass: {
      type: Object,
      required: false,
      default: () => ({ 'scroll-to-top--default': true })
    }
  },
  computed: {
    classObject() {
      return this.scrollToTopClass
    }
  },
  methods: {
    handleScroll() {
      this.showToTop = scrollTop() > 25 * dpr
    },
    scrollToTop() {
      let index = 0
      let step = scrollTop() / 30
      let scrollTopNum = scrollTop() - step
      let time = setInterval(function() {
        index++
        if (index > 32 || scrollTopNum < 0) {
          clearInterval(time)
        }
        scrollTop(scrollTopNum)
        scrollTopNum -= step
      }, 10)
    }
  },
  created() {
    window.addEventListener('scroll', this.handleScroll)
  },
  destroyed() {
    window.removeEventListener('scroll', this.handleScroll)
  }
}
</script>

<style lang="stylus">
@import '../yyvip-stylus/base'
.scroll-to-top
  right 0spx
  bottom 60spx
  z-index 999
  position fixed
  &-enter,
  &-leave-active
    opacity 0
  &-enter-active
  &-leave-active
    transition opacity 1s ease
  &--default
    width 60spx
    height 60spx
    background url('../yyvip-img/scroll-to-top.jpg') center center no-repeat
    background-size 60spx 60spx
</style>

// web_modules/yyvip-react/ScrollToTop/index.jsx
import assign from 'lodash/assign'
import React, { PureComponent } from 'react'
import PropTypes from 'prop-types'
import { Motion, spring } from 'react-motion'
import { display, opacity } from '../style/adapt'
import { getDpr } from '../../yyvip-flexible/utils'
import { scrollTop } from '../../yyvip-utils/checkBrowser'

import './scrollToTop.styl'

export default class ScrollToTop extends PureComponent {
  static defaultProps = {
    dpr: getDpr()
  }

  constructor(...args) {
    super(...args)
    this.state = {
      showToTop: false
    }
    this.handleScroll = this.handleScroll.bind(this)
  }

  componentDidMount() {
    window.addEventListener('scroll', this.handleScroll)
  }

  componentWillUnmount() {
    window.removeEventListener('scroll', this.handleScroll)
  }

  handleScroll() {
    this.setState({
      showToTop: scrollTop() > 25 * this.props.dpr
    })
  }

  handleToTopClick(e) {
    e.stopPropagation()
    let index = 0
    let step = scrollTop() / 30
    let scrollTopNum = scrollTop() - step
    let time = setInterval(function() {
      index++
      if (index > 32 || scrollTopNum < 0) {
        clearInterval(time)
      }
      scrollTop(scrollTopNum)
      scrollTopNum -= step
    }, 10)
  }

  render() {
    const {
      showToTop
    } = this.state
    const {
      classString
    } = this.props
    return (
      <Motion defaultStyle={{ x: 0 }} style={{ x: spring(showToTop ? 100 : 0, { stiffness: 200 }) }}>
        {({ x }) =>
          <div className={`scroll-to-top ${classString || 'scroll-to-top--default'}`} style={assign(display(x), opacity(x))} onClick={this.handleToTopClick}></div>
        }
      </Motion>
    )
  }
}

ScrollToTop.propTypes = {
  classString: PropTypes.string
}
