// web_modules/yyvip-vue/infiniteScroll.vue
<template lang="pug">
.infinite-scroll(:is="tag", ref="scroll")
  slot
</template>

<script>
import { getDpr } from '../yyvip-flexible/utils'
import { delayExec } from '../yyvip-utils/utils'
import { getVisibleHeight, getScrollHeight, getScrollTop, getScrollEventTarget } from '../yyvip-utils/checkBrowser'

export default {
  name: 'infiniteScroll',
  props: {
    distance: {
      type: Number,
      required: false,
      default: 20 * getDpr()
    },
    isScroll: {
      type: Boolean,
      required: false,
      default: true
    },
    onLoadMore: {
      type: Function,
      required: false
    },
    loading: {
      type: Boolean,
      required: false
    },
    tag: {
      type: String,
      required: false,
      default: 'div'
    }
  },
  data() {
    return {
      element: null,
      onScroll: null
    }
  },
  mounted() {
    this.element = getScrollEventTarget(this.$refs.scroll)
    this.onScroll = delayExec(() => {
      if (getScrollHeight(this.element) - getVisibleHeight(this.element) - getScrollTop(this.element) < this.distance && !this.loading && this.isScroll) {
        this.onLoadMore && this.onLoadMore(this.element)
      }
    }, 100)
    this.element.addEventListener('scroll', this.onScroll)
  },
  beforeDestroy() {
    this.destroyScrollEvent()
  },
  methods: {
    // spa + keep-alive: must do this by yourself
    destroyScrollEvent() {
      if (this.element && this.onScroll) this.element.removeEventListener('scroll', this.onScroll)
    }
  }
}
</script>

// web_modules/yyvip-react/InfiniteScroll/index.jsx
import React, { PureComponent} from 'react'
import PropTypes from 'prop-types'
import classnames from 'classnames'
import { getDpr } from '../../yyvip-flexible/utils'
import { delayExec } from '../../yyvip-utils/utils'
import { getVisibleHeight, getScrollHeight, getScrollTop, getScrollEventTarget } from '../../yyvip-utils/checkBrowser'

export default class InfiniteScroll extends PureComponent {
  static defaultProps = {
    tag: 'div',
    isScroll: true,
    distance: 20 * getDpr(),
    styleClass: 'infinite-scroll-default'
  }

  constructor(...args) {
    super(...args)
    this.element = null
    this.onScroll = null
    this.scrollRef = null
  }

  componentDidMount() {
    const { loading, isScroll, distance, onLoadMore } = this.props
    this.element = getScrollEventTarget(this.scrollRef)
    this.onScroll = delayExec(() => {
      if (getScrollHeight(this.element) - getVisibleHeight(this.element) - getScrollTop(this.element) < distance && !loading && isScroll) {
        onLoadMore && onLoadMore(this.element)
      }
    }, 100)
    this.element.addEventListener('scroll', this.onScroll)
  }

  componentWillUnmount() {
    if (this.element && this.onScroll) this.element.removeEventListener('scroll', this.onScroll)
  }

  render() {
    const { styleClass, children } = this.props
    return <this.props.tag className={classnames('infinite-scroll', styleClass)} ref={(target) => { this.scrollRef = target }}>{children}</this.props.tag>
  }
}

InfiniteScroll.propTypes = {
  tag: PropTypes.string,
  loading: PropTypes.bool,
  children: PropTypes.node,
  isScroll: PropTypes.bool,
  distance: PropTypes.number,
  onLoadMore: PropTypes.func,
  styleClass: PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.object,
    PropTypes.string
  ])
}
