// web_modules/yyvip-react/carousel-3d/Slide/index.jsx
import React, {
  PureComponent
} from 'react'
import assign from 'lodash/assign'
import forEach from 'lodash/forEach'
import PropTypes from 'prop-types'
import classnames from 'classnames'

import { adapt } from '../../style/adapt'

import './slide.styl'

export default class Slide extends PureComponent {
  static defaultProps = {
    zIndex: 999
  }

  constructor(...args) {
    super(...args)
    this.handleClick = this.handleClick.bind(this)
  }

  getSideIndex(array) {
    let index = -1
    forEach(array, (t, i) => {
      if (this.matchIndex(t)) index = i
    })
    return index
  }

  matchIndex(index) {
    return index >= 0 ? this.props.index === index : (this.props.total + index) === this.props.index
  }

  calculatePosition(index, positive, zIndex) {
    const indexPos = index + 1
    const y = parseInt(this.props.perspective)
    const z = parseInt(this.props.inverseScaling) + indexPos * 100
    const top = this.props.space === 'auto' ? 0 : parseInt(indexPos * this.props.space)
    const leftRemain = (this.props.space === 'auto') ? parseInt(indexPos * (this.props.width / 1.5)) : parseInt(indexPos * this.props.space)
    const transform = positive ? `translateX(${leftRemain}px) translateZ(-${z}px) rotateY(-${y}deg)` : `translateX(-${leftRemain}px) translateZ(-${z}px) rotateY(${y}deg)`
    return assign({
      top,
      zIndex: zIndex - (Math.abs(index) + 1)
    }, adapt({
      transform
    }, ['Moz', 'Webkit']))
  }

  getStyle(isCurrent) {
    let styles = {}
    if (!isCurrent) {
      const lrStyle = {
        opacity: 1,
        visibility: 'visible'
      }
      const lIndex = this.getSideIndex(this.props.leftIndices)
      const rIndex = this.getSideIndex(this.props.rightIndices)
      if (lIndex >= 0) {
        assign(styles, this.calculatePosition(lIndex, false, this.props.zIndex), lrStyle)
      } else if (rIndex >= 0) {
        assign(styles, this.calculatePosition(rIndex, true, this.props.zIndex), lrStyle)
      }
      if (this.props.hasHiddenSlides) {
        if (this.matchIndex(this.props.leftOutIndex)) {
          styles = this.calculatePosition(this.props.leftIndices.length - 1, false, this.props.zIndex)
        } else if (this.matchIndex(this.props.rightOutIndex)) {
          styles = this.calculatePosition(this.props.rightIndices.length - 1, true, this.props.zIndex)
        }
      }
    }
    return assign(styles, {
      width: `${this.props.slideWidth}px`,
      height: `${this.props.slideHeight}px`,
      borderWidth: `${this.props.border}px`
    }, adapt({
      transition: `transform ${this.props.animationSpeed}ms, opacity ${this.props.animationSpeed}ms, visibility ${this.props.animationSpeed}ms`
    }, ['Moz', 'Webkit'], (item, key, pre) => `-${pre.toLowerCase()}-${item}`))
  }

  handleClick() {
    if (this.props.clickable) this.props.goFar(this.props.index)
  }

  render() {
    const isCurrent = this.props.index === this.props.currentIndex
    const slideStyle = assign(this.getStyle(isCurrent), this.props.style)
    return <div className={classnames('carousel-3d-slide', { current: isCurrent, 'carousel-3d-current': isCurrent, 'carousel-3d-others': !isCurrent })} onClick={this.handleClick} style={slideStyle}>{this.props.children}</div>
  }
}

Slide.propTypes = {
  children: PropTypes.node,
  zIndex: PropTypes.number,
  goFar: PropTypes.func,
  index: PropTypes.number,
  total: PropTypes.number,
  width: PropTypes.number,
  border: PropTypes.number,
  slideWidth: PropTypes.number,
  slideHeight: PropTypes.number,
  animationSpeed: PropTypes.number,
  clickable: PropTypes.bool,
  perspective: PropTypes.number,
  currentIndex: PropTypes.number,
  leftOutIndex: PropTypes.number,
  rightOutIndex: PropTypes.number,
  hasHiddenSlides: PropTypes.bool,
  inverseScaling: PropTypes.number,
  leftIndices: PropTypes.arrayOf(PropTypes.number),
  rightIndices: PropTypes.arrayOf(PropTypes.number),
  space: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.string
  ])
}

// web_modules/yyvip-vue/carousel-3d/slide.vue
<template lang="pug">
.carousel-3d-slide(:style="slideStyle", :class="{current: isCurrent, 'carousel-3d-current': isCurrent, 'carousel-3d-others': !isCurrent}", @click="goTo()")
  slot
</template>

<script>
import assign from 'lodash/assign'

export default {
  name: 'slide',
  props: {
    index: {
      type: Number
    }
  },
  data() {
    return {
      zIndex: 999,
      parent: this.$parent
    }
  },
  computed: {
    isCurrent() {
      return this.index === this.parent.currentIndex
    },
    slideStyle() {
      let styles = {}
      if (!this.isCurrent) {
        const rIndex = this.getSideIndex(this.parent.rightIndices)
        const lIndex = this.getSideIndex(this.parent.leftIndices)
        if (rIndex >= 0 || lIndex >= 0) {
          styles = rIndex >= 0 ? this.calculatePosition(rIndex, true, this.zIndex) : this.calculatePosition(lIndex, false, this.zIndex)
          styles.opacity = 1
          styles.visibility = 'visible'
        }
        if (this.parent.hasHiddenSlides) {
          if (this.matchIndex(this.parent.leftOutIndex)) {
            styles = this.calculatePosition(this.parent.leftIndices.length - 1, false, this.zIndex)
          } else if (this.matchIndex(this.parent.rightOutIndex)) {
            styles = this.calculatePosition(this.parent.rightIndices.length - 1, true, this.zIndex)
          }
        }
      }
      return assign(styles, {
        width: `${this.parent.slideWidth}px`,
        height: `${this.parent.slideHeight}px`,
        'border-width': `${this.parent.border}px`,
        transition: `transform ${this.parent.animationSpeed}ms, opacity ${this.parent.animationSpeed}ms, visibility ${this.parent.animationSpeed}ms`,
        '-webkit-transition': `-webkit-transform ${this.parent.animationSpeed}ms, opacity ${this.parent.animationSpeed}ms, visibility ${this.parent.animationSpeed}ms`
      })
    }
  },
  methods: {
    getSideIndex(array) {
      let index = -1
      array.forEach((pos, i) => {
        if (this.matchIndex(pos)) index = i
      })
      return index
    },
    matchIndex(index) {
      return (index >= 0) ? this.index === index : (this.parent.total + index) === this.index
    },
    calculatePosition(i, positive, zIndex) {
      const iPos = i + 1
      const y = parseInt(this.parent.perspective)
      const z = parseInt(this.parent.inverseScaling) + (iPos * 100)
      const leftRemain = (this.parent.space === 'auto') ? parseInt(iPos * (this.parent.width / 1.5)) : parseInt(iPos * this.parent.space)
      const transform = (positive) ? `translateX(${leftRemain}px) translateZ(-${z}px) rotateY(-${y}deg)` : `translateX(-${leftRemain}px) translateZ(-${z}px) rotateY(${y}deg)`
      const webkitTransform = transform
      const top = this.parent.space === 'auto' ? 0 : parseInt(iPos * this.parent.space)
      return { top, transform, webkitTransform, zIndex: zIndex - (Math.abs(i) + 1) }
    },
    goTo() {
      if (this.parent.clickable === true) {
        this.parent.goFar(this.index)
      }
    }
  }
}
</script>

<style lang="stylus">
@import '../../yyvip-stylus/base'
.carousel-3d-slide
  margin 0
  opacity 0
  text-align left
  overflow hidden
  visibility hidden
  box-sizing border-box
  background-color border-grey
  absolutePos(0, null, null, null)
  border 1PX solid rgba(0, 0, 0, 0.4)
  &.current
    z-index 999
    opacity 1 !important
    transform none !important
    visibility visible !important
</style>
